version: '3'

services:
  crawler:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: crawler
    container_name: crawler
    volumes:
      - .:/app:z
    ports:
      - '80:3000'
    external_links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ngocquang2797
      MONGO_INITDB_ROOT_PASSWORD: 123456789
    volumes:
      - ./mongo:/docker-entrypoint-initdb.d
    ports:
      - '27017:27017'