version: '3'

volumes:
  mongo_data: { }

services:
  crawler:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: crawler
    container_name: crawler
    volumes:
      - .:/app:z
    ports:
      - '80:3000'
    external_links:
      - mongo

  mongodb:
    container_name: mongo
    image: mongo:latest
    restart: always
    env_file:
      - .env
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - '${MONGODB_PORT}:27017'